/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

public class LibraryTest {
    @Test
    public void testSomeLibraryMethod() {
        assertThat(1).isEqualTo(1);
    }
}
